/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package metro.trans.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class BusinessKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 777835943993844070L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BusinessKey\",\"namespace\":\"metro.trans.avro\",\"fields\":[{\"name\":\"TxId\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BusinessKey> ENCODER =
      new BinaryMessageEncoder<BusinessKey>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BusinessKey> DECODER =
      new BinaryMessageDecoder<BusinessKey>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BusinessKey> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BusinessKey> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BusinessKey> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<BusinessKey>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BusinessKey to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BusinessKey from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BusinessKey instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BusinessKey fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence TxId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BusinessKey() {}

  /**
   * All-args constructor.
   * @param TxId The new value for TxId
   */
  public BusinessKey(java.lang.CharSequence TxId) {
    this.TxId = TxId;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return TxId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: TxId = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'TxId' field.
   * @return The value of the 'TxId' field.
   */
  public java.lang.CharSequence getTxId() {
    return TxId;
  }


  /**
   * Sets the value of the 'TxId' field.
   * @param value the value to set.
   */
  public void setTxId(java.lang.CharSequence value) {
    this.TxId = value;
  }

  /**
   * Creates a new BusinessKey RecordBuilder.
   * @return A new BusinessKey RecordBuilder
   */
  public static metro.trans.avro.BusinessKey.Builder newBuilder() {
    return new metro.trans.avro.BusinessKey.Builder();
  }

  /**
   * Creates a new BusinessKey RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BusinessKey RecordBuilder
   */
  public static metro.trans.avro.BusinessKey.Builder newBuilder(metro.trans.avro.BusinessKey.Builder other) {
    if (other == null) {
      return new metro.trans.avro.BusinessKey.Builder();
    } else {
      return new metro.trans.avro.BusinessKey.Builder(other);
    }
  }

  /**
   * Creates a new BusinessKey RecordBuilder by copying an existing BusinessKey instance.
   * @param other The existing instance to copy.
   * @return A new BusinessKey RecordBuilder
   */
  public static metro.trans.avro.BusinessKey.Builder newBuilder(metro.trans.avro.BusinessKey other) {
    if (other == null) {
      return new metro.trans.avro.BusinessKey.Builder();
    } else {
      return new metro.trans.avro.BusinessKey.Builder(other);
    }
  }

  /**
   * RecordBuilder for BusinessKey instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BusinessKey>
    implements org.apache.avro.data.RecordBuilder<BusinessKey> {

    private java.lang.CharSequence TxId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(metro.trans.avro.BusinessKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.TxId)) {
        this.TxId = data().deepCopy(fields()[0].schema(), other.TxId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing BusinessKey instance
     * @param other The existing instance to copy.
     */
    private Builder(metro.trans.avro.BusinessKey other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.TxId)) {
        this.TxId = data().deepCopy(fields()[0].schema(), other.TxId);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'TxId' field.
      * @return The value.
      */
    public java.lang.CharSequence getTxId() {
      return TxId;
    }


    /**
      * Sets the value of the 'TxId' field.
      * @param value The value of 'TxId'.
      * @return This builder.
      */
    public metro.trans.avro.BusinessKey.Builder setTxId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.TxId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'TxId' field has been set.
      * @return True if the 'TxId' field has been set, false otherwise.
      */
    public boolean hasTxId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'TxId' field.
      * @return This builder.
      */
    public metro.trans.avro.BusinessKey.Builder clearTxId() {
      TxId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BusinessKey build() {
      try {
        BusinessKey record = new BusinessKey();
        record.TxId = fieldSetFlags()[0] ? this.TxId : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BusinessKey>
    WRITER$ = (org.apache.avro.io.DatumWriter<BusinessKey>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BusinessKey>
    READER$ = (org.apache.avro.io.DatumReader<BusinessKey>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.TxId);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.TxId = in.readString(this.TxId instanceof Utf8 ? (Utf8)this.TxId : null);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.TxId = in.readString(this.TxId instanceof Utf8 ? (Utf8)this.TxId : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










