/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package metro.trans.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class MetaData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -594178268503184185L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MetaData\",\"namespace\":\"metro.trans.avro\",\"fields\":[{\"name\":\"msgType\",\"type\":\"string\"},{\"name\":\"mdInsertDtTm\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MetaData> ENCODER =
      new BinaryMessageEncoder<MetaData>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MetaData> DECODER =
      new BinaryMessageDecoder<MetaData>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<MetaData> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<MetaData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<MetaData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<MetaData>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this MetaData to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a MetaData from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a MetaData instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static MetaData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence msgType;
   private java.lang.CharSequence mdInsertDtTm;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MetaData() {}

  /**
   * All-args constructor.
   * @param msgType The new value for msgType
   * @param mdInsertDtTm The new value for mdInsertDtTm
   */
  public MetaData(java.lang.CharSequence msgType, java.lang.CharSequence mdInsertDtTm) {
    this.msgType = msgType;
    this.mdInsertDtTm = mdInsertDtTm;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return msgType;
    case 1: return mdInsertDtTm;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: msgType = (java.lang.CharSequence)value$; break;
    case 1: mdInsertDtTm = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'msgType' field.
   * @return The value of the 'msgType' field.
   */
  public java.lang.CharSequence getMsgType() {
    return msgType;
  }


  /**
   * Sets the value of the 'msgType' field.
   * @param value the value to set.
   */
  public void setMsgType(java.lang.CharSequence value) {
    this.msgType = value;
  }

  /**
   * Gets the value of the 'mdInsertDtTm' field.
   * @return The value of the 'mdInsertDtTm' field.
   */
  public java.lang.CharSequence getMdInsertDtTm() {
    return mdInsertDtTm;
  }


  /**
   * Sets the value of the 'mdInsertDtTm' field.
   * @param value the value to set.
   */
  public void setMdInsertDtTm(java.lang.CharSequence value) {
    this.mdInsertDtTm = value;
  }

  /**
   * Creates a new MetaData RecordBuilder.
   * @return A new MetaData RecordBuilder
   */
  public static metro.trans.avro.MetaData.Builder newBuilder() {
    return new metro.trans.avro.MetaData.Builder();
  }

  /**
   * Creates a new MetaData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MetaData RecordBuilder
   */
  public static metro.trans.avro.MetaData.Builder newBuilder(metro.trans.avro.MetaData.Builder other) {
    if (other == null) {
      return new metro.trans.avro.MetaData.Builder();
    } else {
      return new metro.trans.avro.MetaData.Builder(other);
    }
  }

  /**
   * Creates a new MetaData RecordBuilder by copying an existing MetaData instance.
   * @param other The existing instance to copy.
   * @return A new MetaData RecordBuilder
   */
  public static metro.trans.avro.MetaData.Builder newBuilder(metro.trans.avro.MetaData other) {
    if (other == null) {
      return new metro.trans.avro.MetaData.Builder();
    } else {
      return new metro.trans.avro.MetaData.Builder(other);
    }
  }

  /**
   * RecordBuilder for MetaData instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MetaData>
    implements org.apache.avro.data.RecordBuilder<MetaData> {

    private java.lang.CharSequence msgType;
    private java.lang.CharSequence mdInsertDtTm;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(metro.trans.avro.MetaData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.msgType)) {
        this.msgType = data().deepCopy(fields()[0].schema(), other.msgType);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.mdInsertDtTm)) {
        this.mdInsertDtTm = data().deepCopy(fields()[1].schema(), other.mdInsertDtTm);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing MetaData instance
     * @param other The existing instance to copy.
     */
    private Builder(metro.trans.avro.MetaData other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.msgType)) {
        this.msgType = data().deepCopy(fields()[0].schema(), other.msgType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.mdInsertDtTm)) {
        this.mdInsertDtTm = data().deepCopy(fields()[1].schema(), other.mdInsertDtTm);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'msgType' field.
      * @return The value.
      */
    public java.lang.CharSequence getMsgType() {
      return msgType;
    }


    /**
      * Sets the value of the 'msgType' field.
      * @param value The value of 'msgType'.
      * @return This builder.
      */
    public metro.trans.avro.MetaData.Builder setMsgType(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.msgType = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'msgType' field has been set.
      * @return True if the 'msgType' field has been set, false otherwise.
      */
    public boolean hasMsgType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'msgType' field.
      * @return This builder.
      */
    public metro.trans.avro.MetaData.Builder clearMsgType() {
      msgType = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'mdInsertDtTm' field.
      * @return The value.
      */
    public java.lang.CharSequence getMdInsertDtTm() {
      return mdInsertDtTm;
    }


    /**
      * Sets the value of the 'mdInsertDtTm' field.
      * @param value The value of 'mdInsertDtTm'.
      * @return This builder.
      */
    public metro.trans.avro.MetaData.Builder setMdInsertDtTm(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.mdInsertDtTm = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'mdInsertDtTm' field has been set.
      * @return True if the 'mdInsertDtTm' field has been set, false otherwise.
      */
    public boolean hasMdInsertDtTm() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'mdInsertDtTm' field.
      * @return This builder.
      */
    public metro.trans.avro.MetaData.Builder clearMdInsertDtTm() {
      mdInsertDtTm = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MetaData build() {
      try {
        MetaData record = new MetaData();
        record.msgType = fieldSetFlags()[0] ? this.msgType : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.mdInsertDtTm = fieldSetFlags()[1] ? this.mdInsertDtTm : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MetaData>
    WRITER$ = (org.apache.avro.io.DatumWriter<MetaData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MetaData>
    READER$ = (org.apache.avro.io.DatumReader<MetaData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.msgType);

    out.writeString(this.mdInsertDtTm);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.msgType = in.readString(this.msgType instanceof Utf8 ? (Utf8)this.msgType : null);

      this.mdInsertDtTm = in.readString(this.mdInsertDtTm instanceof Utf8 ? (Utf8)this.mdInsertDtTm : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.msgType = in.readString(this.msgType instanceof Utf8 ? (Utf8)this.msgType : null);
          break;

        case 1:
          this.mdInsertDtTm = in.readString(this.mdInsertDtTm instanceof Utf8 ? (Utf8)this.mdInsertDtTm : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










